name: dart_rss
version: 1.1.1+1
description: dart-rss is a rss parser for RSS1.0/RSS2.0/Atom. It also support Dublin-Core, Content, Syndication additional modules. This libary is forked from webfeed(https://github.com/witochandra/webfeed).
homepage: https://github.com/sudame/dart-rss
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  xml: ^5.0.2
  http: ^0.13.0
  meta: ^1.3.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.5
